osx_image: xcode9.4
language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
    - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
before_script:
    - set -o pipefail
script:
    - swiftlint
    - xcodebuild test -workspace ./HUDMakerKit.xcworkspace -scheme HUDMakerKitTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X' | xcpretty -c

